templates/home.twig
Updated the "Sharing is Caring" Soundcloud link to point to the new LMMS group.
=> Update Soundcloud Group Link on Homepage

public/lsp/utils.php
Here is a rewrite of the parser function, so we don't need to use all sorts of hacks to make it work :)
I'd like a second set of eyes to look at the code (@Lukas-W or @tresf ) before I merge this, just in case.
=> Link parser rewrite

templates/competitions.twig, templates/showcase.twig
- Moves the "Best of LMMS v3" competition to "past competitions"
- Adds the bandcamp playlist to the "showcase" page
=> Update competitions and showcase pages with BOL v3

templates/competitions.twig
=> Fix caret orientation

templates/get-involved.twig
Also split the mailing list panel into two paragraphs so the two align properly:
=> Add info about the discord server on the getting involved page

public/lsp/utils.php
Added support for parsing https://clyp.it links to iframes on LSP
=> Parse clyp.it links on LSP

public/lsp/sidebar.php
Removed labels from username/password inputs in LSP, fixed <input> tags (these are void elements which must not be closed with end tags, as specified in http://w3c.github.io/html-reference/syntax.html#void-elements)
=> Updated login sidebar in LSP

public/css/style.css
Centered login button and register link, improved spacing
Before:
After:
=> Updated LSP login sidebar (CSS layout)

public/community.php
Since groups don't actually seem to exist on SoundCloud, I simply found the link for the SoundCloud "lmmsio" account, and replaced the URL there. This was a really quick and easy edit hopefully.
=> Groups no longer exist on SoundCloud

templates/competitions.twig, templates/showcase.twig
fixes #227 
Added Bol v4 to the showcase, updated the competitions page
=> Update info about Best of LMMS vol 4

templates/download/linux.twig, templates/get-involved.twig, templates/home.twig
* one wrong link to the github wiki
* a few final point missing (for consistency)
I found these while translating the website into French.
=> A few fixes against the futur website

templates/download/linux.twig
There are some minor problems with the website and I will stage the fix here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lmms/lmms.io/273)
=> Minor fixes

translations/messages.ru.xlf
There is no "Функционал" word in Russian meaning Functionality, but there is "Функциональность"
=> Fix translation typo

translations/messages.ru.xlf
my previous patch contains misprint — fix it
=> fixup misprint

public/lsp/add_file.php, public/lsp/dbo.php, public/lsp/register.php, public/lsp/user_settings.php, public/lsp/utils.php
A few improvements and features
**Features:**
Added sorting by comments
Improved pagination
**Fixes:**
Disabled registering with a html encodable username to avoid broken accounts
Improved consistency and made some parts of the site easier to understand
Made realname optional during registration
Added a server check for username/full name length
Fixed file traversal attack
=> General improvements

public/lsp/dbo.php
~~Since this pull request changes a lot of the SQL queries (mostly just formats them better but also some other changes were made for some) I would like this commit to be reviewed before being accepted in case i broke something and did not notice (I've checked a lot of stuff myself and have not found anything but i want to make sure).~~
Everything appears to work fine.
Changes:
1) Improved readability of large SQL queries
2) All data which is a parameter of show_basic_file_info() now has the fields `comments`,`rating` and `rating_count` so we can comment out the lines which add any missing fields in the show_basic_file_info() function
=> Made SQL queries easier to read and improved file's SQL query slightly

translations/messages.de.xlf
* Add missing translation for the header
* Add missing translation for the sections:
- Website & Docs
- Translations
* Fix several typos
=> Update german translation for get-involved page

config/routes.yaml
=> Add BoLresults to routes

public/under-maintenance.html, templates/head.twig
Things added/changed:
- Update Font Awesome to v6.4.2.
- Closes #365.
=> Update Font Awesome to v6.4.2

README.md, lib/Artifacts.php, lib/Platform.php, lib/PlatformParser.php, lib/Releases.php, templates/download/index.twig, templates/download/pull-request.twig
* Fix listing of `linux-x86_64` builds
* Add ARM64 Linux downloads
* Add MSVC downloads
* Simplify button descriptions
=> Update nightlies buttons

public/under-maintenance.html, templates/foot.twig, templates/head.twig
Update the twitter logo to the new X logo
Updated font-awesome CDN to the latest (6.4.2 -> 6.7.2).
=> Update fontawesome and twitter logo

public/css/style.min.css, public/css/style.scss
This is the PR for #398
Some changes for the first commit:
1. Implement CSS changes for a dark theme
2. Variable-ize some colors
3. Ran a formatter through the .scss file
edit for GH autolinking: related #398
=> Dynamic theming + dark theme

public/css/style.css
This PR changes the selector a little bit
Fixes #406
=> Fix theming artifact under nav bar

public/css/style.css
This PR changes some styling of a few elements that require more contrast or better color choices to ensure maximum readability and recognition. _tl;dr, passing WCAG 2.0 AA_.
Originally, this PR is opened to hopefully close #340, it may grow in scope to extend to other UI elements as well, perhaps even touching LSP or Forum styling if needed.
However, this needs some feedback from the other maintainers if such change is needed or if we leave it be, so I'm including @rubiefawn and @tresf
=> Increase contrast on UI elements and pass WCAG 2.0 AA test
