LMMS/lmms.io

templates/download/index.twig

This fixes #133. It prevents auto-scrolling when (auto-)selecting an OS/distro tab. 
However, this is done by not writing a tab select into `location.hash`, so when clicking a distro tab, the selected tab will not occur in the URL but just keep saying `/download/#linux`.
Linking to directly to a distro (e.g. 'https://lmms.io/download/#linux-debian`) will still work.

Download page: Don't scroll to selected tab

---

README.md

A minuscule change, but when setting this up locally, I skimmed over the instructions and missed the part where it said to run it from `lmms.io/public`. This change makes it more visible so it's not as easily missed.
What do you think?

Make server path to serve from more visible

---

composer.lock

I ran `php composer.phar update guzzlehttp/ringphp` fo fix #186. This updates ringphp from version 1.0.5 to 1.1.0. All changes in this PR were generated by composer.
- Code changes: https://github.com/guzzle/RingPHP/compare/1.0.5...1.1.0
- Changelog: https://github.com/guzzle/RingPHP/blob/1.1.0/CHANGELOG.md 
I skimmed over the changes and think they should be safe to apply. Please take another look to confirm since I don't know this codebase yet :)
Fixes #186

Update ringphp to fix some php 7 incompatibilities

---

cron/hourly/git_maintenance_tasks_lock
cron/hourly/tasks-lmms
dev/git_maintenance_tasks
tasks/lmms/01-project-year
tasks/lmms/02-contributors
tasks/lmms/99-error.disabled

This adds an hourly cron job to maintain the repository `lmms`. Is an access to GitHub set up already? A commit preparing the affected files should be done first.

Maintenance tasks for repository lmms

---

cron/git_maintenance_tasks

Allow switches among branches without removing the local repository, per https://github.com/LMMS/lmms.io/pull/198#discussion_r101218217.
Do not merge until the task that updates `CONTRIBUTORS` is fixed.

Switch to target branch

---

templates/competitions.twig

I've ended up doing most of the communication with submitters when there are problems (broken links, invalid entries, etc.). Right now I'm asking for project files from some artists to confirm that their submissions are made with LMMS. Listing my email on the competitions page should lend me some credibility so submitters don't think I'm trying to steal their project files.

Add email address on competitions page

---

templates/get-involved.twig

We shuffled the channels around a bit and #welcome got deleted. #rules is what we want to link to now.

Update Discord link to point to #rules

---

lib/Releases.php
templates/download/index.twig
templates/download/linux.twig
views.php

Adds the long overdue Linux `.AppImage` buttons to the downloads page.
* Moves the platform-specific download options (e.g. `apt-get install lmms`) to "Other options", collapsed by default.
* Adds Stable/Beta download button for Linux `.AppImage` files
**Note:** This should be merged only after `1.2.0-RC5` is released.

Add Linux downloads

---

public/locale/zh_CN/LC_MESSAGES/messages.po

```html
<a href="http：//kxstudio.sourceforge.net/Repositories#Ubuntu">KXStudio 软件源</a>
```
rendered as `https://lmms.io/download/http%EF%BC%9A//kxstudio.sourceforge.net/Repositories#Ubuntu` in my FireFox
`http：//kxstudio.sourceforge.net/Repositories#Ubuntu` should be `http://kxstudio.sourceforge.net/Repositories#Ubuntu`  (replace U+FF1A Unicode Character 'FULLWIDTH COLON' `'：'` with `':'`)

fix zh-CN malformed kxstuido link

---

public/lsp/dbo.php
public/lsp/download_file.php

Fixes #276
Known issues:
- Because the way LSP stores the file name is problematic, if a file is named `You & Me`, the database will record `You &amp; Me` instead. I think the problem lies here: https://github.com/LMMS/lmms.io/blob/6fe9697435a6a546801bcd35a610e4ac85e28b08/public/lsp/add_file.php#L31
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/lmms/lmms.io/279)

dbo: correctly escape the download link

---

composer.lock

Fixes security vulnerability CVE-2020-5255. Closes PR #299 that updates to a new major version which is probably not what we want.

Update symfony/http-foundation from 4.4.1 to 4.4.8

---

public/lsp/dbo.php
public/lsp/register.php
public/lsp/utils.php

This pull request has four changes:
1) Fix a security flaw which allows the creation of admin accounts.
2) Fixes a old XSS method involving the version of a file, the fix replaces all "dangerous characters" with a dot, this should not effect the common users since the only dangerous character in a normal version string is a dot
3) Checks if the account creation has been successful before saying that the creation was a success, this may help with the confusion of some users in the rare case the database fails to insert the new account.
4) Adds a server side check which makes sure that the user who is rating the file is not the owner of the file.
Example of the old xss method: https://lmms.io/lsp/?action=show&file=15972
Username of an account I created using the admin account creation flaw: …

CRITICAL: Patch ability to create admin accounts + other general fixes

---

src/Controller/PortalController.php
templates/wiki.twig

per @liushuyu 's request, here's a simple page that notifies users about removing the mediawiki instance, with an automatic 30 second redirect to docs.lmms.io.

Add a wiki redirect page

---

templates/home.twig

They have a specific way to search for tagged songs. The former link would just show songs called "LMMS", which excluded a lot of (usually higher production) songs.

Use correct SoundCloud link

---

templates/download/index.twig

This PR replaces all instances of "Nightly" on the downloads page with "Alpha". This an attempt to prevent continuing confusion from people downloading the somewhat old public 1.30 alpha build and erroneously thinking it is a proper Nightly version.
This is intended to be a short term solution while #351 is in stasis.

Replace "Nightly" text with "Alpha" on download page

---

.env
config/packages/cache.yaml
config/packages/github_api.yaml
config/routes.yaml
config/services.yaml
lib/Artifacts.php
lib/Asset.php
lib/GitHubMarkdownEngine.php
lib/GithubDownloadClient.php
lib/Platform.php
lib/Releases.php
src/Controller/DownloadController.php
templates/download/error.twig
templates/download/index.twig
templates/download/linux.twig
templates/download/pull-request.twig

The main changes in this PR:
* Add actual tip-of-master nightlies to the downloads page, and rename the alpha builds from "Nightly" to "Alpha".
* Add a page for downloading pull request builds.
* Add a redirect route for downloading GitHub Actions artifacts without the user needing to log in to GitHub (similar to https://nightly.link/). This is required for the nightly and pull request downloads.
Other changes:
* Updated the library classes and download controller to use Symfony's autowiring dependency injection.
* Moved the repository owner and name information into a config file.
* Fixed various catch blocks to refer to `Exception` in the root namespace.
* Added the jumbo into the download error page, so it looks a little less broken.
* Added types to various functions.
* Refactored the …

Add downloads for nightlies and pull requests

---

lib/Artifacts.php
src/Controller/DownloadController.php

Recently the website stopped working with nightly downloads... The error suggests that something with the response header in symphony was wrong.
```
[Tue Sep 12 21:53:50 2023] [critical] Uncaught PHP Exception ErrorException: "Warning: Header may not contain NUL bytes" at /Users/owner/lmms.io/vendor/symfony/http-foundation/Response.php line 342
```
Investigation shows that `getArtifactDownloadURL(...)` calls `$this->client->repo()->artifacts()->download(...)` which returns the binary file (not the URL as the name might suggest) however, when Symphony casts this to a `Response`, the header is missing.  I'm not sure what recently changed to cause this, but crafting the `Response` object manually seems to fix this.
One upside of crafting a `Response` manually this way that it forces us to …

Fix nightly downloads

---

lib/Artifacts.php
lib/GithubDownloadClient.php
lib/HttpClientPlugin/MethodPlugin.php
lib/HttpClientPlugin/UriRecordPlugin.php

This PR allows downloading artifacts uploaded using version 4 of the `upload-artifact` action. See LMMS/lmms#7263.
We use a new technique for extracting the redirect location for artifact downloads. Previously, we searched for hardcoded strings within the host name of redirects, but this is the second time the host has changed and broken the downloads. Now, we follow the redirects as normal, and return the URL once we get a `200` response rather than a `302`. This is done with `HEAD` requests, in order to avoid actually downloading the artifact on the server.
Unfortunately, this breaks downloads for version 3 artifacts. The server for these responds with `200` as normal for `GET` requests to artifacts, but responds with `404` to `HEAD` requests for some reason. However, I hope this new …

Support downloading v4 artifacts

---

lib/Artifacts.php
templates/download/index.twig

I've started to remove 32 bit support in the CI. If this gets through, nightlies won't have 32 bit artefacts anymore for windows. There should be a warning to explain the missing artifacts. Per https://github.com/LMMS/lmms/issues/6614#issuecomment-2122841250 by @tresf 
TODO:

Add warning for missing 32 bit downloads for nightly

---

public/css/style.min.css
public/css/style.scss

Previously, the download buttons looked like this:
but the unnevenness of the download button annoyed me so i made it look like this:
I seriously don't understand why the style.scss diff is so large, all i did was add one line (186).

Make the download button widths the same.

---

public/css/style.css

This PR improves the coloring of the buttons, alerts, and code blocks in the download page. Along with variable-izing more colors.

Improve download page colors + add vars for them

---

public/css/style.css
templates/download/index.twig
templates/download/linux.twig
templates/download/pull-request.twig

Resolves #404 (lol) by updating download button colors to match https://github.com/LMMS/lmms/pull/5166. The colors used here are defined in the OKLCH color space and have their brightness and saturation adjusted to look mostly consistent.
```css
--bg-btn-dl-stable:  oklch(65% 0.15 152);
--bg-btn-dl-alpha:   oklch(60% 0.15 250);
--bg-btn-dl-nightly: oklch(56% 0.2  290);
--bg-btn-dl-pr:      oklch(72% 0.15  75);
```
This PR also cleans up the `.btn-dl` family of rules a bit.

Update download button colors to match lmms/#5166

---

public/css/style.css

I broke download buttons in #405 due to a few typos. This would have been caught with a nonzero amount of testing beyond screwing around in inspect element, so that's on me. This PR should restore the shapes of the download buttons as well as make the alpha buttons use their colors properly.

Fix my crimes against download buttons

---

README.md
dev/windows/setup.ps1

This PR (which now uses the correct base branch) adds a Windows-specific setup script located in `dev/windows/setup.ps1` using PowerShell.
The script's actions is as follows:
1. Create the variables `$phpDir` and `$fullPhpDir`
2. Asks for the PHP install directory, because it isn't standardized in Windows
3. Checks if the given path exists
4. Checks if the PHP executable exists
5. If the script was started in the `dev/windows` folder, go to the project root
6. Create the variables `$composerInstallerUrl` and `$composerInstallerPath`
7. Downloads composer's installer using the two variables aforementioned
8. Checks if composer exists after the download
9. Runs composer's installer using the PHP in `$fullPhpDir`
10. Runs the `install` command from composer to install dependencies
11. Cleans …

Add Windows setup script

---

public/css/style.css

This PR intends to close #411 by adding a new set of overridable variables able to be set using CSS `@supports` queries, ensuring the browser sets the proper styling if it can indeed use the function

add theming compatibility for older browsers
